# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buffer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='buffer.proto',
  package='Client',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x62uffer.proto\x12\x06\x43lient\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x03(\t\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x03(\t\")\n\rInsertRequest\x12\n\n\x02id\x18\x01 \x03(\x05\x12\x0c\n\x04name\x18\x02 \x03(\t\")\n\rModifyRequest\x12\n\n\x02id\x18\x01 \x03(\x05\x12\x0c\n\x04name\x18\x02 \x03(\t\"\x19\n\x0b\x46indRequest\x12\n\n\x02id\x18\x01 \x03(\x05\"\x1b\n\rDeleteRequest\x12\n\n\x02id\x18\x01 \x03(\x05\x32\xf1\x02\n\x07Greeter\x12\x36\n\x08SayHello\x12\x14.Client.HelloRequest\x1a\x12.Client.HelloReply\"\x00\x12;\n\rSayHelloAgain\x12\x14.Client.HelloRequest\x1a\x12.Client.HelloReply\"\x00\x12>\n\x0finsertNewClient\x12\x15.Client.InsertRequest\x1a\x12.Client.HelloReply\"\x00\x12;\n\x0cupdateClient\x12\x15.Client.ModifyRequest\x1a\x12.Client.HelloReply\"\x00\x12\x37\n\nfindClient\x12\x13.Client.FindRequest\x1a\x12.Client.HelloReply\"\x00\x12;\n\x0c\x64\x65leteClient\x12\x15.Client.DeleteRequest\x1a\x12.Client.HelloReply\"\x00'
)




_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='Client.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='Client.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=53,
)


_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='Client.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Client.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=83,
)


_INSERTREQUEST = _descriptor.Descriptor(
  name='InsertRequest',
  full_name='Client.InsertRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Client.InsertRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='Client.InsertRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=126,
)


_MODIFYREQUEST = _descriptor.Descriptor(
  name='ModifyRequest',
  full_name='Client.ModifyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Client.ModifyRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='Client.ModifyRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=169,
)


_FINDREQUEST = _descriptor.Descriptor(
  name='FindRequest',
  full_name='Client.FindRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Client.FindRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=196,
)


_DELETEREQUEST = _descriptor.Descriptor(
  name='DeleteRequest',
  full_name='Client.DeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Client.DeleteRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=225,
)

DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['InsertRequest'] = _INSERTREQUEST
DESCRIPTOR.message_types_by_name['ModifyRequest'] = _MODIFYREQUEST
DESCRIPTOR.message_types_by_name['FindRequest'] = _FINDREQUEST
DESCRIPTOR.message_types_by_name['DeleteRequest'] = _DELETEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'buffer_pb2'
  # @@protoc_insertion_point(class_scope:Client.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'buffer_pb2'
  # @@protoc_insertion_point(class_scope:Client.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

InsertRequest = _reflection.GeneratedProtocolMessageType('InsertRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSERTREQUEST,
  '__module__' : 'buffer_pb2'
  # @@protoc_insertion_point(class_scope:Client.InsertRequest)
  })
_sym_db.RegisterMessage(InsertRequest)

ModifyRequest = _reflection.GeneratedProtocolMessageType('ModifyRequest', (_message.Message,), {
  'DESCRIPTOR' : _MODIFYREQUEST,
  '__module__' : 'buffer_pb2'
  # @@protoc_insertion_point(class_scope:Client.ModifyRequest)
  })
_sym_db.RegisterMessage(ModifyRequest)

FindRequest = _reflection.GeneratedProtocolMessageType('FindRequest', (_message.Message,), {
  'DESCRIPTOR' : _FINDREQUEST,
  '__module__' : 'buffer_pb2'
  # @@protoc_insertion_point(class_scope:Client.FindRequest)
  })
_sym_db.RegisterMessage(FindRequest)

DeleteRequest = _reflection.GeneratedProtocolMessageType('DeleteRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEREQUEST,
  '__module__' : 'buffer_pb2'
  # @@protoc_insertion_point(class_scope:Client.DeleteRequest)
  })
_sym_db.RegisterMessage(DeleteRequest)



_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='Client.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=228,
  serialized_end=597,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='Client.Greeter.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SayHelloAgain',
    full_name='Client.Greeter.SayHelloAgain',
    index=1,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='insertNewClient',
    full_name='Client.Greeter.insertNewClient',
    index=2,
    containing_service=None,
    input_type=_INSERTREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='updateClient',
    full_name='Client.Greeter.updateClient',
    index=3,
    containing_service=None,
    input_type=_MODIFYREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='findClient',
    full_name='Client.Greeter.findClient',
    index=4,
    containing_service=None,
    input_type=_FINDREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='deleteClient',
    full_name='Client.Greeter.deleteClient',
    index=5,
    containing_service=None,
    input_type=_DELETEREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
